-   id: commit-msg-hook
    name: commit-msg-hook
    description: Checks if commit message matches the chaos-hub commit rules
    entry: commit-msg-hook
    language: python
    types: [python, text]
  